<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
    <AssemblyName>Flow.Launcher.Plugin.Snippets</AssemblyName>
    <PackageId>Flow.Launcher.Plugin.Snippets</PackageId>
    <Authors>yu-xiaoyao</Authors>
    <PackageProjectUrl>https://github.com/yu-xiaoyao/Flow.Launcher.Plugin.Snippets</PackageProjectUrl>
    <RepositoryUrl>https://github.com/yu-xiaoyao/Flow.Launcher.Plugin.Snippets</RepositoryUrl>
    <PackageTags>flow-launcher flow-plugin</PackageTags>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputType>exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Images\\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Languages\\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Flow.Launcher.Plugin" Version="4.5.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

</Project>
